# Helper functions for loading and comparing Python Delicatessen reference results

#' Load a fixture JSON file from tests/testthat/fixtures/
#'
#' @param name The fixture name (without .json extension)
#' @return A list with the fixture data
load_fixture <- function(name) {
  path <- testthat::test_path("fixtures", paste0(name, ".json"))
  jsonlite::fromJSON(path, simplifyVector = TRUE)
}

#' Compare R M-estimation results against Python Delicatessen reference values
#'
#' Validates theta, full variance matrix, asymptotic variance, bread matrix,
#' and confidence interval bounds against a JSON fixture generated by Python
#' Delicatessen.
#'
#' The reading is testthat's own, which is the aggregate relative difference
#' over the entries that are not already bit-equal, not an element-wise one. The
#' distinction matters for the matrices: their off-diagonals sit orders of
#' magnitude below the diagonal, so a large diagonal carries the scale the whole
#' block is measured against. The aggregate reading is kept because the
#' element-wise one, on this corpus, is dominated by float noise on entries that
#' are analytically zero rather than by any disagreement about the estimates.
#' Where a comparison sits close to its tolerance the measured margin is
#' recorded in a comment at the call site.
#'
#' The variance and asymptotic variance blocks are the ones that drift between
#' platforms, because an equation whose bread is differentiated numerically
#' carries that derivative's error into the sandwich, where it is amplified.
#' `variance_tolerance` loosens those two blocks alone, so a call site can give
#' them cross-platform room while theta, the bread, and the interval bounds stay
#' pinned at `tolerance`.
#'
#' @param m A fitted MEstimator object (after calling estimate())
#' @param fixture_name Name of the fixture file to compare against
#' @param tolerance Numeric tolerance for comparisons (default 1e-6)
#' @param variance_tolerance Numeric tolerance for the variance and asymptotic
#'   variance blocks (defaults to `tolerance`)
expect_python_match <- function(
  m,
  fixture_name,
  tolerance = 1e-6,
  variance_tolerance = tolerance
) {
  ref <- load_fixture(fixture_name)

  # theta estimates
  testthat::expect_equal(
    unname(m@theta),
    ref$theta,
    tolerance = tolerance,
    label = paste0(fixture_name, ": theta")
  )

  # Full variance matrix (not just diagonal)
  testthat::expect_equal(
    unname(m@variance),
    as.matrix(ref$variance),
    tolerance = variance_tolerance,
    label = paste0(fixture_name, ": variance")
  )

  # Asymptotic variance
  if (!is.null(ref$asymptotic_variance) && !is.null(m@asymptotic_variance)) {
    testthat::expect_equal(
      unname(m@asymptotic_variance),
      as.matrix(ref$asymptotic_variance),
      tolerance = variance_tolerance,
      label = paste0(fixture_name, ": asymptotic_variance")
    )
  }

  # Bread matrix
  if (!is.null(ref$bread)) {
    testthat::expect_equal(
      unname(m@bread),
      as.matrix(ref$bread),
      tolerance = tolerance,
      label = paste0(fixture_name, ": bread")
    )
  }

  # Confidence intervals
  if (!is.null(ref$ci_lower) && !is.null(ref$ci_upper)) {
    ci <- confidence_intervals(m)
    testthat::expect_equal(
      unname(ci[, "lower"]),
      ref$ci_lower,
      tolerance = tolerance,
      label = paste0(fixture_name, ": ci_lower")
    )
    testthat::expect_equal(
      unname(ci[, "upper"]),
      ref$ci_upper,
      tolerance = tolerance,
      label = paste0(fixture_name, ": ci_upper")
    )
  }

  invisible(m)
}
