# Tests for t-distribution inference under finite_correction
#
# When finite_correction is set, both delicatessen and deli switch confidence
# intervals and P-values from the standard normal to the t-distribution with
# df = n_obs - n_params, matching the finite-sample adjustment of the variance.
# These tests confirm that behavior against the Python reference.
#
# The GMMEstimator carries the same t-distribution behavior. Its degrees of
# freedom are n_obs - n_params, where n_params is the number of parameters (the
# length of init), not the number of moment conditions. The over-identified
# fixture gmm_overid_finite_correction exercises that path with more moment
# conditions than parameters.
#
# Fixtures ee_mean_finite_correction, ee_regression_finite_correction, and
# gmm_overid_finite_correction were generated by
#   fixtures/generate_finite_correction_fixtures.py
# via `uv run --with-editable . python <script>` from the worktree root.

fit_mean_finite_correction <- function() {
  ref <- load_fixture("ee_mean_finite_correction")
  y <- ref$y
  psi <- function(theta) {
    matrix(y - theta[1], nrow = 1)
  }
  m <- MEstimator(
    stacked_equations = psi,
    init = ref$init,
    finite_correction = ref$finite_correction
  )
  estimate(m)
}

fit_regression_finite_correction <- function() {
  ref <- load_fixture("ee_regression_finite_correction")
  X <- ref$X
  y <- ref$y
  psi <- function(theta) {
    residuals <- y - as.numeric(X %*% theta)
    t(X * residuals)
  }
  m <- MEstimator(
    stacked_equations = psi,
    init = ref$init,
    finite_correction = ref$finite_correction
  )
  estimate(m)
}

fit_gmm_overid_finite_correction <- function() {
  ref <- load_fixture("gmm_overid_finite_correction")
  # Two-column design (intercept, endogenous regressor) against a three-column
  # instrument matrix (intercept, two instruments): three moment conditions for
  # two parameters, so the system is over-identified.
  design <- cbind(1, ref$x)
  instruments <- cbind(1, ref$z1, ref$z2)
  y <- ref$y
  psi <- function(theta) {
    residuals <- y - as.numeric(design %*% theta)
    t(instruments * residuals)
  }
  g <- GMMEstimator(
    stacked_equations = psi,
    init = ref$init,
    finite_correction = ref$finite_correction
  )
  estimate(g)
}

# Point estimates and variance (HC1 correction already supported) -------------

test_that("finite_correction fit reproduces Python theta and variance (mean)", {
  ref <- load_fixture("ee_mean_finite_correction")
  m <- fit_mean_finite_correction()

  expect_equal(unname(m@theta), ref$theta, tolerance = 1e-6)
  expect_equal(unname(m@variance), as.matrix(ref$variance), tolerance = 1e-6)
  expect_equal(m@n_obs, ref$n_obs)
  expect_equal(m@n_params, ref$n_params)
})

test_that("finite_correction fit reproduces Python theta and variance (regression)", {
  ref <- load_fixture("ee_regression_finite_correction")
  m <- fit_regression_finite_correction()

  # 1e-5 rather than 1e-6: the R and Python solvers stop at slightly different
  # points, so theta and the variance built from it differ past the sixth digit.
  expect_equal(unname(m@theta), ref$theta, tolerance = 1e-5)
  expect_equal(unname(m@variance), as.matrix(ref$variance), tolerance = 1e-5)
  expect_equal(m@n_obs, ref$n_obs)
  expect_equal(m@n_params, ref$n_params)
})

# Confidence intervals use the t-distribution under finite_correction ---------

test_that("confidence_intervals() use the t-distribution under finite_correction (mean)", {
  ref <- load_fixture("ee_mean_finite_correction")
  m <- fit_mean_finite_correction()

  ci <- confidence_intervals(m, alpha = ref$alpha)
  expect_equal(unname(ci[, "lower"]), ref$ci_lower, tolerance = 1e-6)
  expect_equal(unname(ci[, "upper"]), ref$ci_upper, tolerance = 1e-6)
})

test_that("confidence_intervals() use the t-distribution under finite_correction (regression)", {
  ref <- load_fixture("ee_regression_finite_correction")
  m <- fit_regression_finite_correction()

  ci <- confidence_intervals(m, alpha = ref$alpha)
  expect_equal(unname(ci[, "lower"]), ref$ci_lower, tolerance = 1e-6)
  expect_equal(unname(ci[, "upper"]), ref$ci_upper, tolerance = 1e-6)
})

test_that("t-distribution CIs are wider than the normal-approximation CIs", {
  ref <- load_fixture("ee_regression_finite_correction")
  m <- fit_regression_finite_correction()

  ci <- confidence_intervals(m, alpha = ref$alpha)
  se <- sqrt(diag(m@variance))
  z_lower <- m@theta - qnorm(1 - ref$alpha / 2) * se
  z_upper <- m@theta + qnorm(1 - ref$alpha / 2) * se

  # The t-distribution has heavier tails, so the interval is strictly wider.
  expect_true(all(ci[, "lower"] < z_lower))
  expect_true(all(ci[, "upper"] > z_upper))
})

# P-values use the t-distribution under finite_correction --------------------

test_that("p_values() use the t-distribution under finite_correction (mean)", {
  ref <- load_fixture("ee_mean_finite_correction")
  m <- fit_mean_finite_correction()

  p <- p_values(m, null = ref$null)
  expect_equal(unname(p), ref$p_values, tolerance = 1e-6)
})

test_that("p_values() use the t-distribution under finite_correction (regression)", {
  ref <- load_fixture("ee_regression_finite_correction")
  m <- fit_regression_finite_correction()

  p <- p_values(m, null = ref$null)
  expect_equal(unname(p), ref$p_values, tolerance = 1e-6)
})

# Z-scores are unaffected by the reference distribution ----------------------

test_that("z_scores() match Python regardless of finite_correction (regression)", {
  ref <- load_fixture("ee_regression_finite_correction")
  m <- fit_regression_finite_correction()

  # 1e-5 rather than 1e-6: z-scores inherit the small solver difference in theta.
  z <- z_scores(m, null = ref$null)
  expect_equal(unname(z), ref$z_scores, tolerance = 1e-5)
})

# S-values inherit the t-distribution through the P-values -------------------

test_that("s_values() follow the t-distribution P-values under finite_correction (regression)", {
  ref <- load_fixture("ee_regression_finite_correction")
  m <- fit_regression_finite_correction()

  # 1e-5 rather than 1e-6: s-values inherit the small solver difference in theta.
  s <- s_values(m, null = ref$null)
  expect_equal(unname(s), ref$s_values, tolerance = 1e-5)
})

# Over-identified GMMEstimator carries the same t-distribution inference -------

test_that("finite_correction GMM fit reproduces Python theta and variance (over-identified)", {
  ref <- load_fixture("gmm_overid_finite_correction")
  g <- fit_gmm_overid_finite_correction()

  expect_equal(unname(g@theta), ref$theta, tolerance = 1e-6)
  expect_equal(unname(g@variance), as.matrix(ref$variance), tolerance = 1e-6)
  expect_equal(g@n_obs, ref$n_obs)
  # n_params is the number of parameters (two), not the number of moment
  # conditions (three), which sets the t degrees of freedom below.
  expect_equal(g@n_params, ref$n_params)
})

test_that("confidence_intervals() use the t-distribution under finite_correction (GMM over-identified)", {
  ref <- load_fixture("gmm_overid_finite_correction")
  g <- fit_gmm_overid_finite_correction()

  ci <- confidence_intervals(g, alpha = ref$alpha)
  expect_equal(unname(ci[, "lower"]), ref$ci_lower, tolerance = 1e-6)
  expect_equal(unname(ci[, "upper"]), ref$ci_upper, tolerance = 1e-6)
})

test_that("p_values() use the t-distribution under finite_correction (GMM over-identified)", {
  ref <- load_fixture("gmm_overid_finite_correction")
  g <- fit_gmm_overid_finite_correction()

  # Both fixture P-values sit in the interior of (0, 1) (0.031 and 0.143), so
  # the comparison is above the absolute tolerance floor of all.equal.
  p <- p_values(g, null = ref$null)
  expect_equal(unname(p), ref$p_values, tolerance = 1e-6)
})

test_that("GMM t-distribution CIs are wider than the normal-approximation CIs (over-identified)", {
  ref <- load_fixture("gmm_overid_finite_correction")
  g <- fit_gmm_overid_finite_correction()

  ci <- confidence_intervals(g, alpha = ref$alpha)
  se <- sqrt(diag(g@variance))
  z_lower <- g@theta - qnorm(1 - ref$alpha / 2) * se
  z_upper <- g@theta + qnorm(1 - ref$alpha / 2) * se

  # A method that silently used the normal distribution would produce these
  # narrower bounds. The heavier t tails must strictly widen every interval.
  expect_true(all(ci[, "lower"] < z_lower))
  expect_true(all(ci[, "upper"] > z_upper))
})

test_that("GMM t-distribution P-values differ from the normal-approximation P-values (over-identified)", {
  ref <- load_fixture("gmm_overid_finite_correction")
  g <- fit_gmm_overid_finite_correction()

  p_t <- p_values(g, null = ref$null)
  z <- z_scores(g, null = ref$null)
  p_normal <- 2 * pnorm(-abs(z))

  # The t reference gives larger tail probabilities than the normal, so a
  # normal fallback would fail this comparison.
  expect_true(all(p_t > p_normal))
  expect_false(isTRUE(all.equal(
    unname(p_t),
    unname(p_normal),
    tolerance = 1e-6
  )))
})

test_that("GMM t degrees of freedom are n_obs minus n_params, not n_obs minus moments", {
  ref <- load_fixture("gmm_overid_finite_correction")
  g <- fit_gmm_overid_finite_correction()

  ci <- confidence_intervals(g, alpha = ref$alpha)
  se <- sqrt(diag(g@variance))
  # Recover the critical value the fit used from the interval half-width.
  cv <- unname((ci[, "upper"] - g@theta) / se)

  # df uses the two parameters (n - 2 = 18), not the three moment conditions
  # (n - 3 = 17). The two references are numerically distinct.
  expect_equal(
    cv,
    rep(qt(1 - ref$alpha / 2, df = ref$n_obs - ref$n_params), 2),
    tolerance = 1e-8
  )
  cv_moments <- qt(1 - ref$alpha / 2, df = ref$n_obs - 3)
  expect_false(isTRUE(all.equal(cv[1], cv_moments, tolerance = 1e-6)))
})
